version: "3"
services:
    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./:/app
        command: >
          sh -c "
                 wait-for-it db:5432 &&
                 python manage.py migrate &&
                 python manage.py runserver 0.0.0.0:8000"
        env_file:
            - .env
        depends_on:
            - db
        restart: always
    db:
        image: "postgres"
        container_name: db_service
        env_file:
            - .env
        ports:
            - "5433:5432"
        volumes:
            - ./count_unique_words.sql:/docker-entrypoint-initdb.d/count_unique_words.sql
            - ./count_words.sql:/docker-entrypoint-initdb.d/count_words.sql
            - db_data:/var/lib/postgresql/data/
        restart: always
volumes:
    db_data:
        driver: local
